AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Naming/ConstantName:
  Enabled: false

Layout/LineLength:
  Max: 120
